name: Github Actions running unit tests

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    name: Running units tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
